### ISSUE TITLE
Not able to run Zephyr 7B Gemma with 4 80GB A100s

### ISSUE THREAD

**Issue by TJ-Solergibert** [huggingface/alignment-handbook#132]
I'm not able to run Zephyr 7B Gemma with 4 80GB A100s. I get the following error:
```
RuntimeError: The size of tensor a (0) must match the size of tensor b (24576) at non-singleton dimension 1
```
After running:
```
ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/deepspeed_zero3.yaml scripts/run_sft.py recipes/zephyr-7b-gemma/sft/config_full.yaml
```
As can be seen, I've just modified `num_processes ` and I tested `zero3_init_flag: false`
```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

I've seen this related issue, (#57), but none of the solutions work. 

Hope we find a solution soon for the members of the 4 GPU cluster club! 🤗
