### ISSUE TITLE
Full parameter fine-tuning keeps consuming system RAM and lead to crash 

### ISSUE THREAD

**Issue by xiyang-aads-lilly** [huggingface/alignment-handbook#201]
I am using alignment handbook to perform a full parameter fine-tuning of llama3 models with Deepspeed stage 2 on my own dataset which is relatively large (400k+ records). 
The training was performed on a slurm cluster with two nodes (each has 4 H100 GPUs).
I have noticed that during the training, the system memory utilization keeps increasing even though I set torch_empty_cache_steps=500. 
I wonder if there is something wrong with the HF trainer? Any suggestions how to fix/debug? 
There is also a similar issue at https://github.com/huggingface/transformers/issues/30119

- Below is the system ram usage report from wandb:

![Screenshot 2024-10-15 at 10 41 49 AM](https://github.com/user-attachments/assets/1201d5ad-26ee-4d15-81c1-9ef33128bba0)
![Screenshot 2024-10-15 at 10 41 46 AM](https://github.com/user-attachments/assets/200b887c-38bd-40f9-a160-e61c14c25870)
![Screenshot 2024-10-15 at 10 41 43 AM](https://github.com/user-attachments/assets/4fee96b4-fd08-4073-a17a-dd7d4cfd8e34)

- my config:
```yaml
# Model arguments
model_name_or_path: ~/models/Meta-Llama-3-8B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
chat_template: "{{ bos_token }}{% if messages[0]['role'] == 'system' %}{% set system_message = '### System Instruction: ' + messages[0]['content'] | trim + '' %}{% set messages = messages[1:] %}{% else %}{% set system_message = '' %}{% endif %}{{ bos_token + system_message }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '### Context: ' + message['content'] | trim + '' }}{% elif message['role'] == 'assistant' %}{{ '### Result: ' + message['content'] | trim + ' ' + eos_token }}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '### Result: ' }}{% endif %}"
dataset_mixer:
  ~/data/processed_data_open_sourced_xml_to_text/merged_open_sourced_xml_to_text_dataset: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 4
dataloader_num_workers: 2

# SFT trainer config
bf16: true
do_eval: true
# evaluation_strategy: epoch
eval_strategy: epoch
max_grad_norm: 1.0
# gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
log_level: info
logging_steps: 5
logging_strategy: steps
learning_rate: 2.0e-05
lr_scheduler_type: cosine_with_min_lr # cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr: 5e-6
optim: adamw_torch # adamw_torch paged_adamw_32bit galore_adamw lion_32bit
optim_target_modules: all-linear
weight_decay: 0.01
max_seq_length: 12800
packing: false
dataset_num_proc: 16
max_steps: -1
num_train_epochs: 1
output_dir: /~/alignment-handbook/experiments/models/llama3
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1 # this is per device, you need to manual calculate global batch by per device * gas * gpu * node
gradient_accumulation_steps: 8
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb # - tensorboard
save_strategy: "steps"
save_steps: 500
torch_empty_cache_steps: 500
save_total_limit: 30
seed: 42
warmup_ratio: 0.1
```

- training launch script (brief version)
```sh

#!/bin/bash

#SBATCH --job-name=train
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --gpus-per-task=4
#SBATCH --cpus-per-task=32
#SBATCH --mem=512gb
#SBATCH --time=96:00:00
#SBATCH --output=output
#SBATCH --partition=batch

# apptainer
CONTAINER=pt2402.sif
TRAIN_CONF=config.yaml
DEEPSPEED_CONF=deepspeed_zs2.json
CMD=torchrun \
    --nproc_per_node=$SLURM_GPUS_ON_NODE  \
    --nnode=$SLURM_JOB_NUM_NODES \
    --node_rank=$SLURM_NODEID  \
    --master_addr=$PRIMARY \
    --master_port=$PRIMARY_PORT \
    ${ROOT}/scripts/run_sft.py \
    $TRAIN_CONF \
    --deepspeed=$DEEPSPEED_CONF \
    --tee=3

srun --jobid $SLURM_JOB_ID apptainer exec --nv $CONTAINER bash -c $CMD
```

- deepspeed config:
```json
{
    "fp16": {
        "enabled": false,
        "loss_scale": 0,
        "auto_cast": false,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "consecutive_hysteresis": false,
        "min_loss_scale": 1
    },

    "bf16": {
        "enabled": true
    },

    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "weight_decay": "auto",
            "betas": "auto",
            "eps": "auto",
            "torch_adam": true,
            "adam_w_mode": true
        }
    },

    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_min_lr": 1e-8,
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto",
            "total_num_steps": "auto"
        }
    },

    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 5e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": "auto",
        "contiguous_gradients": true,
        "round_robin_gradients": true
    },

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 20000000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```
